version: '3.8'

services:
  chronoledger-gateway:
    image: chronoledger-gateway
    build:
      context: .
      dockerfile: src/ChronoLedger.Gateway/Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION:-Release}
    ports:
      - "8081:8080"
    environment:
      - DatabaseSqlConnectionString=Host=postgres;Database=ledgerdb;Username=postgres;Password=yourpassword
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres  

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ledgerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
